### ISSUE TITLE
Deleting a Nurse Visit deletes the student

### ISSUE THREAD

**Issue by lkozloff** [francoisjacquet/rosariosis#216] opened 2017-12-01 03:32 UTC
In the current version of RosarioSIS deleting a Nurse Visit on the Medical tab leads to a prompt "Are you sure you want to Delete that student?". If you click "OK" the student is deleted.

**Expected Behavior**:
Only the Nurse Visit is deleted.

**Steps to reproduce**
- Log in to the demo site at https://www.rosariosis.org/demonstration
- Log in as administrator/administrator
- Select a student record (Students->Find, then choose a student)
- Browse to the Medical tab and add a Nurse visit
- Click the **-** to delete the recently added Nurse visit
- Observe that the dialog prompts you to delete the student.

**Comment by francoisjacquet** [comment] 2017-12-01 21:59
Hello @lkozloff,

Thank you for reporting this bug and the steps to reproduce it.
This regression must be present since the Delete student enhancement has been introduced.

It will be fixed in RosarioSIS 3.6.

**Closed as completed** 2017-12-02 15:34 UTC
